services:
  - type: web
    name: farmbot-backend
    env: node
    buildCommand: cd farmbot-backend && pnpm install
    startCommand: cd farmbot-backend && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 5000 